#pragma once

#include "simint/vectorization/vectorization.h"

#define SIMINT_OSTEI_MAXAM 4
#define SIMINT_OSTEI_MAXDER 1
#define SIMINT_OSTEI_DERIV1_MAXAM -1
#define SIMINT_OSTEI_MAX_WORKSIZE_BCONT  (SIMINT_SIMD_ROUND(SIMINT_NSHELL_SIMD*21025))
#define SIMINT_OSTEI_MAX_WORKSIZE_CONT   (SIMINT_SIMD_ROUND(418905))
#define SIMINT_OSTEI_MAX_WORKSIZE_PRIM   (SIMINT_SIMD_LEN*79965)
#define SIMINT_OSTEI_MAX_WORKSIZE        (SIMINT_OSTEI_MAX_WORKSIZE_BCONT + SIMINT_OSTEI_MAX_WORKSIZE_PRIM + SIMINT_OSTEI_MAX_WORKSIZE_CONT)
#define SIMINT_OSTEI_MAX_WORKMEM         (SIMINT_OSTEI_MAX_WORKSIZE * sizeof(double))

